version: '3.5'

services:  
  tt-web-a:
    container_name: tt-web-a
    restart: unless-stopped
    image: territorytools/web-main-site
    build:
      context: .
      dockerfile: ./Web/MainSite/Dockerfile
    volumes:
      - "${DataVolume}:/data"
      - "${DataVolume}/secrets:/app/secrets"
    networks:
      - main  
    ports:
      - "127.0.0.1:${SlotPort}:80"
    environment:
      - ASPNETCORE_URLS=$ASPNETCORE_URLS
      - ASPNETCORE_ENVIRONMENT=$ASPNETCORE_ENVIRONMENT
      - ASPNETCORE_HOSTINGSTARTUPASSEMBLIES=Microsoft.AspNetCore.ApplicationInsights.HostingStartup
      - APPLICATIONINSIGHTS_CONNECTION_STRING=$APPLICATIONINSIGHTS_CONNECTION_STRING
      - Authentication:Google:ClientId=$GoogleClientId
      - Authentication:Google:ClientSecret=$GoogleClientSecret
      - ConnectionStrings:MainDbContextConnection=$MainDbContextConnection
      - Users=$Users
      - AuthorizedUsers=$AuthorizedUsers
      - AdminUsers=$AdminUsers
      - Authentication:Microsoft:ClientSecret=$MicrosoftClientSecret
      - Authentication:Microsoft:ClientId=$MicrosoftClientId
      - AlbaHost=$AlbaHost
      - AlbaUser=$AlbaUser
      - AlbaPassword=$AlbaPassword
      - AlbaAccount=$AlbaAccount
      - LetsEncrypt:Email=$LetsEncryptEmail
      - LetsEncrypt:UseStaging=$LetsEncryptUseStaging
      - LetsEncrypt:Domains=$LetsEncryptDomains
      - LetsEncrypt:CountryName=$LetsEncryptCountryName
      - LetsEncrypt:Locality=$LetsEncryptLocality
      - LetsEncrypt:Organization=$LetsEncryptOrganization
      - LetsEncrypt:OrganizationUnit=$LetsEncryptOrganizationUnit
      - LetsEncrypt:State=$LetsEncryptState
      - DataVolume=$DataVolume
      - HttpPort=$HttpPort
      - SslPort=$SslPort
      - NoSsl=$NoSsl
      - UrlShortenerDomain=$UrlShortenerDomain
      - AzureAppId=$AzureAppId
      - AzureClientSecret=$AzureClientSecret
      - TT_AreaNames=$TT_AreaNames
      - CompletionMapUrl=$CompletionMapUrl
      - AuthMessageSender:SendGridUser
      - AuthMessageSender:SendGridKey
      - AuthMessageSender:AuthEmailFromEmailAddress
      - AuthMessageSender:AuthEmailFromName
      - AuthMessageSender:AuthEmailTo
      - AuthMessageSender:PurchaseManager
      - AuthMessageSender:BuyerEmail
      - HOST_NAME=$HOST_NAME
      - DefaultPhoneTerritorySourceDocumentId=$DefaultPhoneTerritorySourceDocumentId
      - DefaultPhoneTerritorySourceSheetName=$DefaultPhoneTerritorySourceSheetName
      - SharedPhoneTerritoryEmailAddress=$SharedPhoneTerritoryEmailAddress
      - SharedPhoneTerritoryFullName=$SharedPhoneTerritoryFullName
      - SmsApiUserName=$SmsApiUserName
      - SmsApiPassword=$SmsApiPassword
      - SmsFromPhoneNumber=$SmsFromPhoneNumber
      - SmsAdminRecipient=$SmsAdminRecipient
      - SlotPort=$SlotPort
      - Features:UserSelfComplete=$Features_UserSelfComplete
      - OldMobileServerFqdn=$OldMobileServerFqdn
      - NewMobileServerFqdn=$NewMobileServerFqdn      
      - TerritoryApiHostAndPort=$TerritoryApiHostAndPort
      - TerritoryApiBaseUrl=$TerritoryApiBaseUrl
      - MobileBaseUrl=https://mobile.territorytools.org
      - SharedPhoneTerritoryLink=$SharedPhoneTerritoryLink
      - GoogleMyMapLink=$GoogleMyMapLink

networks:
  main:
    name: tt-network