version: '3.8'

include:
- ../../docker-compose/tt-api.yml
- ../../docker-compose/tt-mob.yml
- ../../docker-compose/tt-web.yml
- ../../docker-compose/db.yml

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - ../..:/workspaces:cached
    #network_mode: service:db
    command: sleep infinity

  proxy:
    image: nginx
    #ports:
    #- 81:80
    #- 127.0.0.1:7000:80
    #- 7000:80
    volumes:
    - ./nginx-proxy.conf:/etc/nginx/nginx.conf:ro
    - ./nginx-proxy-shared.conf:/etc/nginx/sites-enabled/shared:ro
    #- ./data/tt-app-prod-a:/var/www/html
    # - /data/nginx-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    network_mode: host

  static-files: 
    image: nginx
    ports:
    #- 8007:80
    - 127.0.0.1:8007:80
    volumes:
    - ./nginx-static.conf:/etc/nginx/nginx.conf:ro
    - /data/tt-app-prod-a:/usr/share/nginx/html/app
    #- /data/tt-app-prod-a:/var/www


# TODO: Maybe add a network?
# extra_hosts:
#     - "host.docker.internal:host-gateway"