name: Territory Tools Web Docker Image CI 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image for Territory Tools Web
      run: docker build . --file Web/MainSite/Dockerfile --tag territorytools:$(date +%s)
