name: Territory Tools Web Docker Image CI 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set Up Docker Image Tag
      run: echo "image_tag=$(date +%s)" >> $GITHUB_ENV
    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Build the Docker image for Territory Tools Web
      run: docker build . --file Web/MainSite/Dockerfile --tag marcdurham/territorytools:${{ env.image_tag }}
    - name: Push Docker Image to Docker hub
      run: docker push marcdurham/territorytools:${{ env.image_tag }}
      
      
   
#- name: Set up gcloud Cloud SDK environment
  # You may pin to the exact commit or the version.
  # uses: google-github-actions/setup-gcloud@877d4953d2c70a0ba7ef3290ae968eb24af233bb
 # uses: google-github-actions/setup-gcloud@v0.6.0
 
