name: .NET

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
##    - uses: actions/checkout@v2
##    - name: Setup .NET
##      uses: actions/setup-dotnet@v1
##      with:
##        dotnet-version: 5.0.x
##    - name: Restore dependencies
##      run: dotnet restore Web/MainSite/Web.MainSite.csproj
##    - name: Generate (Localized) Resource Files
##      run: pwsh Web/MainSite/Resources/Generate-ResourceFiles.ps1
##    - name: Build Territory Tools Main Web Site
##      run: dotnet build --no-restore Web/MainSite/Web.MainSite.csproj
#    - name: Test
#      run: dotnet test --no-build --verbosity normal
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: marcdurham/territorytools:latest
        file: Web/MainSite/Dockerfile
